blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/youngcoder45
    about: Please use discussions or contact the maintainer for general questions.
